version: '3'
services:
    db:
        image: mysql
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
    app:
        build: docker/fpm
        environment:
            XDEBUG_CONFIG: "remote_enable=1 remote_connect_back=1"
            PHP_IDE_CONFIG: "serverName=Docker"
        volumes:
            - .:/var/www
    nginx:
        build: docker/nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www
