version: '3'
services:
    db:
        image: mysql
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
    app:
        build: docker/fpm
        environment:
            XDEBUG_CONFIG: "discover_client_host=1"
            XDEBUG_MODE: "debug"
            PHP_IDE_CONFIG: "serverName=Docker"
        volumes:
            - .:/var/www/app
            - composercache:/root/.composer
    nginx:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
volumes:
    composercache:
